version: '3.1'
services:

  mongo:
    container_name: mongoParquimetro
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: parquimetro
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  web:
    image: tech:3.0
    depends_on:
      - mongo
    ports:
      - 8080:8080

